// ----------------------- AUTO-GENERATED -----------------------
// DO NOT EDIT DIRECTLY. This file is generated by publish-ios.sh
// Source: scripts/templates/Package.swift.erb
// --------------------------------------------------------------

// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "TSLocationManager",
    platforms: [.iOS(.v12.0)],
    products: [
        // Consumers import this product.
        .library(name: "TSLocationManager", targets: ["TSLocationManagerKit"])
    ],
    dependencies: [
        // SPM dependency on TSBackgroundFetch (range; avoid churn)
        .package(url: "https://github.com/transistorsoft/transistor-background-fetch", from: "4.0.0")
    ],
    targets: [
        // Binary target (your XCFramework)
        .binaryTarget(
            name: "TSLocationManagerBinary",
            url: "https://github.com/transistorsoft/native-background-geolocation/releases/download/4.0.0-beta.9/TSLocationManager.xcframework.zip",
            checksum: "b874715dc679c78d78f32c76987dd68d7805ec36264ce71c43a06b0003b7746b"
        ),

        // Wrapper Swift target that reexports the binary + TSBackgroundFetch
        .target(
            name: "TSLocationManagerKit",
            dependencies: [
                "TSLocationManagerBinary",
                .product(name: "TSBackgroundFetch", package: "transistor-background-fetch")
            ],
            path: "Sources/TSLocationManagerKit"
        )
    ]
)
