// swift-tools-version: 5.9
// ----------------------- AUTO-GENERATED -----------------------
// DO NOT EDIT DIRECTLY. This file is generated by publish-ios.sh
// Source: scripts/templates/Package.swift.erb
// --------------------------------------------------------------

import PackageDescription

let package = Package(
    name: "TSLocationManager",
    platforms: [
        .iOS(.v12)
    ],
    products: [
        // Consumers import this product.
        .library(name: "TSLocationManager", targets: ["TSLocationManagerKit"])
    ],
    dependencies: [
        // SPM dependency on TSBackgroundFetch (allow patch updates)
        .package(
            url: "https://github.com/transistorsoft/transistor-background-fetch.git",
            .upToNextMinor(from: "4.0.6")
        )
    ],
    targets: [
        .binaryTarget(
            name: "TSLocationManager",
            url: "https://github.com/transistorsoft/native-background-geolocation/releases/download/4.0.19/TSLocationManager.xcframework.zip",
            checksum: "ff266d7c15c01516bc138640cc6b95534565215bb8648c0ad0c14cb5adcefa9c"
        ),

        // Wrapper Swift target that reexports the binary + TSBackgroundFetch
        .target(
            name: "TSLocationManagerKit",
            dependencies: [
                "TSLocationManager",
                .product(name: "TSBackgroundFetch", package: "transistor-background-fetch")
            ],
            path: "Sources/TSLocationManagerKit"
        )
    ]
)
