// ----------------------- AUTO-GENERATED -----------------------
// DO NOT EDIT DIRECTLY. This file is generated by publish-ios.sh
// --------------------------------------------------------------

@_exported import TSBackgroundFetch
@_exported import TSLocationManager
