name: Help Wanted
description: I need assistance
title: "[Help Wanted]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support request.
  - type: checkboxes
    id: terms
    attributes:
      label: Required Reading
      description: "- I have read the [Philosophy of Operation](https://docs.transistorsoft.com/help/philosophy/) and [Debugging](https://docs.transistorsoft.com/help/debugging/) guides\n- I am aware of the API Reference ([Swift](https://docs.transistorsoft.com/swift/BGGeo/) | [Kotlin](https://docs.transistorsoft.com/kotlin/BGGeo/))\n- I am aware of the Changelogs ([iOS](./blob/master/CHANGELOG-iOS.md) | [Android](./blob/master/CHANGELOG-Android.md))"
      options:
        - label: Confirmed
          required: true
  - type: input
    id: version
    attributes:
      label: SDK Version
      description: What version of the SDK are you running?
      placeholder: "iOS: Podfile.lock or Package.swift · Android: build.gradle (do not enter 'latest')"
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: Mobile operating-system(s)
      description: Which mobile operating-system(s) is this about?
      options:
        - label: iOS
        - label: Android
    validations:
      required: true
  - type: input
    id: device-info
    attributes:
      label: Device Manufacturer(s) and Model(s)
      description: What is the device model(s) and manufacturer(s)
      placeholder: eg Google Pixel 6, iPhone 13 Pro
    validations:
      required: true
  - type: input
    id: device-os
    attributes:
      label: Device operating-systems(s)
      description: Affected device operating system
      placeholder: eg iOS 18.1, Android 13
    validations:
      required: true
  - type: input
    id: build-tooling
    attributes:
      label: Build tooling versions
      description: Relevant build-tool versions for your platform
      placeholder: "iOS: Xcode 16.2 / Swift 5.9 · Android: Gradle 8.7 / Kotlin 2.0 / AGP 8.3"
  - type: textarea
    id: what-happened
    attributes:
      label: What do you require assistance about?
    validations:
      required: true
  - type: textarea
    id: config-swift
    attributes:
      label: "[Optional] iOS — Swift Config / Code"
      description: Provide the Config you're using with `bgGeo.ready(...)` along with any other relevant Swift code.
      placeholder: "Paste your Swift Config or code here, eg: bgGeo.ready(reset: false) { config in ... }.\n\nYour code will be automatically syntax-highlighted"
      render: swift
    validations:
      required: false
  - type: textarea
    id: config-kotlin
    attributes:
      label: "[Optional] Android — Kotlin Config / Code"
      description: Provide the Config you're using with `bgGeo.ready(...)` along with any other relevant Kotlin code.
      placeholder: "Paste your Kotlin Config or code here, eg: bgGeo.ready(reset = false) { ... }.\n\nYour code will be automatically syntax-highlighted"
      render: kotlin
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "[Optional] Relevant log output"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: "include iOS / Android logs\n- Android: $ adb logcat -s TSLocationManager:V\n- iOS: Xcode console logs\n- Logs emailed via bgGeo.logger.emailLog(to:)"
      render: shell
    validations:
        required: false
